# Use the official Golang image to create a build artifact.
FROM golang:1.19 as builder

# Copy local code to the container image.
WORKDIR /app
COPY go.mod ./
COPY main.go ./

# Build the binary.
RUN CGO_ENABLED=0 GOOS=linux go build -v -o server

# Use a Docker multi-stage build to create a lean production image.
FROM alpine:3

# Copy the binary to the production image from the builder stage.
COPY --from=builder /app/server /server

# Run the web service on container startup.
CMD ["/server"]
